# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: /myportfolio

# Title of the Site
title: Svetoslav Pandeliev
# Description of the Site
description: tech Writer & Docs as Code Enthusiast
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /myportfolio/assets/images/moritz-kindler-unsplash.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: slavipande@gmail.com
facebook_username: 
twitter_username: slavipande
instagram_username: 
linkedin_username: svetoslav-pandeliev
github_username:  spandeliev
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Svetoslav Pandeliev
# URL for the Image of the Author
author-image: /myportfolio/assets/images/avatar1.png
# 60 Words About the Author
author-about: Tech Writer & Docs as Code Enthusiast
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/spandeliev

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
